development:
  access_key: AKIAIPVWKTDH57OBQFRA
  secret_access_key: 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
  bucket: 'in-search-of-sunrise-test'

test:
  access_key: AKIAIPVWKTDH57OBQFRA
  secret_access_key: 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
  bucket: 'in-search-of-sunrise-test'

production:
  access_key: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: 'in-search-of-sunrise'
