development:
  sessions:
    default:
      database: isos_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: isos_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        safe: true
        skip_version_check: true
